"""Constants for the transmission module"""

SET_DTYPES = {
    "DAILYTIMEBRACKET": int,
    "EMISSION":str,
    "FUEL":str,
    "MODE_OF_OPERATION":int,
    "REGION":str,
    "SEASON":str,
    "STORAGE":str,
    "TECHNOLOGY":str,
    "TIMESLICE":str,
    "YEAR":int,
}

USA_TRN_BA_DICT_FROM = {
    'TRNUSAMIUSAPJ' : 'USASW',
    'TRNUSAMIUSASO' : 'USASA',
    'TRNUSAMIUSASP' : 'USASA',
    'TRNUSAMIUSASW' : 'USASW',
    'TRNUSAMIUSATV' : 'USASA',
    'TRNUSAMIUSAWA' : 'USAMW',
    'TRNUSAPJUSATV' : 'USARW',
    'TRNUSASWUSAWA' : 'USAMW',
    'TRNUSASWUSAWM' : 'USASN',
}

USA_TRN_BA_DICT_TO = {
    'TRNCANMBUSAMI' : 'USAMW',
    'TRNCANMBUSASW' : 'USAMW',
    'TRNCANONUSAMI' : 'USARM',
    'TRNCANONUSAPJ' : 'USARE',
    'TRNCANSKUSAMI' : 'USAMW',
    'TRNCANSKUSASW' : 'USAMW',
    'TRNUSAAIUSAMI' : 'USASW',
    'TRNUSAAIUSASW' : 'USASN',
    'TRNUSACEUSAPJ' : 'USARE',
    'TRNUSACWUSAPJ' : 'USARW',
    'TRNUSADUUSAPJ' : 'USARW',
    'TRNUSAEPUSASW' : 'USASS',
    'TRNUSAERUSAMI' : 'USASA',
    'TRNUSAERUSASW' : 'USASS',
    'TRNUSAGLUSAMI' : 'USASW',
    'TRNUSALGUSAMI' : 'USASW',
    'TRNUSALGUSAPJ' : 'USARW',
    'TRNUSAMIUSAPJ' : 'USARW',
    'TRNUSAMIUSASW' : 'USASN',
    'TRNUSANYUSAPJ' : 'USARE',
    'TRNUSAPNUSASW' : 'USASS',
    'TRNUSAPOUSASW' : 'USASN',
    'TRNUSASPUSASW' : 'USASS',
}