AccumulatedAnnualDemand:
    indices: [REGION,FUEL,YEAR]
    type: param
    dtype: float
    default: 0
AnnualEmissionLimit:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: -1
AnnualExogenousEmission:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: 0
AvailabilityFactor:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 1
CapacityFactor:
    indices: [REGION,TECHNOLOGY,TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 1
CapacityOfOneTechnologyUnit:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
CapacityToActivityUnit:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 1
CapitalCost:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
CapitalCostStorage:
    indices: [REGION,STORAGE,YEAR]
    type: param
    dtype: float
    default: 0
Conversionld:
    indices: [TIMESLICE,DAYTYPE]
    type: param
    dtype: float
    default: 0
Conversionlh:
    indices: [TIMESLICE,DAILYTIMEBRACKET]
    type: param
    dtype: float
    default: 0
Conversionls:
    indices: [TIMESLICE,SEASON]
    type: param
    dtype: float
    default: 0
DAILYTIMEBRACKET:
    dtype: int
    type: set
DaysInDayType:
    indices: [SEASON,DAYTYPE,YEAR]
    type: param
    dtype: float
    default: 7
DaySplit:
    indices: [DAILYTIMEBRACKET,YEAR]
    type: param
    dtype: float
    default: 0.00137
DAYTYPE:
    dtype: int
    type: set
DepreciationMethod:
    indices: [REGION]
    type: param
    dtype: float
    default: 1
DiscountRate:
    indices: [REGION]
    type: param
    dtype: float
    default: 0.05
DiscountRateIdv:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 0.05
DiscountRateStorage:
    indices: [REGION,STORAGE]
    type: param
    dtype: float
    default: 0.05
EMISSION:
    dtype: str
    type: set
EmissionActivityRatio:
    indices: [REGION,TECHNOLOGY,EMISSION,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
EmissionsPenalty:
    indices: [REGION,EMISSION,YEAR]
    type: param
    dtype: float
    default: 0
FixedCost:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
FUEL:
    dtype: str
    type: set
InputActivityRatio:
    indices: [REGION,TECHNOLOGY,FUEL,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
MinStorageCharge:
    indices: [REGION,STORAGE,YEAR]
    type: param
    dtype: float
    default: 0
MODE_OF_OPERATION:
    dtype: int
    type: set
ModelPeriodEmissionLimit:
    indices: [REGION,EMISSION]
    type: param
    dtype: float
    default: -1
ModelPeriodExogenousEmission:
    indices: [REGION,EMISSION]
    type: param
    dtype: float
    default: 0
OperationalLife:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 1
OperationalLifeStorage:
    indices: [REGION,STORAGE]
    type: param
    dtype: float
    default: 0
OutputActivityRatio:
    indices: [REGION,TECHNOLOGY,FUEL,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
REGION:
    dtype: str
    type: set
REMinProductionTarget:
    indices: [REGION,YEAR]
    type: param
    dtype: float
    default: 0
ReserveMargin:
    indices: [REGION,YEAR]
    type: param
    dtype: float
    default: 1
ReserveMarginTagFuel:
    indices: [REGION,FUEL,YEAR]
    type: param
    dtype: float
    default: 0
ReserveMarginTagTechnology:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
ResidualCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
ResidualStorageCapacity:
    indices: [REGION,STORAGE,YEAR]
    type: param
    dtype: float
    default: 999
RETagFuel:
    indices: [REGION,FUEL,YEAR]
    type: param
    dtype: float
    default: 0
RETagTechnology:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
SEASON:
    dtype: int
    type: set
SpecifiedAnnualDemand:
    indices: [REGION,FUEL,YEAR]
    type: param
    dtype: float
    default: 0
SpecifiedDemandProfile:
    indices: [REGION,FUEL,TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 0
STORAGE:
    dtype: str
    type: set
StorageLevelStart:
    indices: [REGION,STORAGE]
    type: param
    dtype: float
    default: 0
StorageMaxChargeRate:
    indices: [REGION,STORAGE]
    type: param
    dtype: float
    default: 0
StorageMaxDischargeRate:
    indices: [REGION,STORAGE]
    type: param
    dtype: float
    default: 0
TECHNOLOGY:
    dtype: str
    type: set
TechnologyFromStorage:
    indices: [REGION,TECHNOLOGY,STORAGE,MODE_OF_OPERATION]
    type: param
    dtype: float
    default: 0
TechnologyToStorage:
    indices: [REGION,TECHNOLOGY,STORAGE,MODE_OF_OPERATION]
    type: param
    dtype: float
    default: 0
TIMESLICE:
    dtype: str
    type: set
TotalAnnualMaxCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: -1
TotalAnnualMaxCapacityInvestment:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: -1
TotalAnnualMinCapacity:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TotalAnnualMinCapacityInvestment:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TotalTechnologyAnnualActivityLowerLimit:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: 0
TotalTechnologyAnnualActivityUpperLimit:
    indices: [REGION,TECHNOLOGY,YEAR]
    type: param
    dtype: float
    default: -1
TotalTechnologyModelPeriodActivityLowerLimit:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: 0
TotalTechnologyModelPeriodActivityUpperLimit:
    indices: [REGION,TECHNOLOGY]
    type: param
    dtype: float
    default: -1
TradeRoute:
    indices: [REGION,FUEL,YEAR]
    type: param
    dtype: float
    default: 0
VariableCost:
    indices: [REGION,TECHNOLOGY,MODE_OF_OPERATION,YEAR]
    type: param
    dtype: float
    default: 0
YEAR:
    dtype: int
    type: set
YearSplit:
    indices: [TIMESLICE,YEAR]
    type: param
    dtype: float
    default: 0
AnnualEmissions:
    indices: [REGION,EMISSION,YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
AccumulatedNewCapacity:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
AnnualFixedOperatingCost:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
AnnualTechnologyEmission:
    indices: [REGION, TECHNOLOGY, EMISSION, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
AnnualTechnologyEmissionByMode:
    indices: [REGION, TECHNOLOGY, EMISSION, MODE_OF_OPERATION, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
AnnualVariableOperatingCost:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
CapitalInvestment:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
Demand:
    indices: [REGION, TIMESLICE, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
DiscountedSalvageValue:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
DiscountedTechnologyEmissionsPenalty:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
NewCapacity:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
NewStorageCapacity:
    indices: [REGION, STORAGE, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
NumberOfNewTechnologyUnits:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
ProductionByTechnology:
    indices: [REGION, TIMESLICE, TECHNOLOGY, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
ProductionByTechnologyAnnual:
    indices: [REGION, TECHNOLOGY, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
RateOfActivity:
    indices: [REGION, TIMESLICE, TECHNOLOGY, MODE_OF_OPERATION, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
RateOfProductionByTechnology:
    indices: [REGION, TIMESLICE, TECHNOLOGY, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
RateOfProductionByTechnologyByMode:
    indices: [REGION, TIMESLICE, TECHNOLOGY, MODE_OF_OPERATION, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
RateOfUseByTechnology:
    indices: [REGION, TIMESLICE, TECHNOLOGY, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
RateOfUseByTechnologyByMode:
    indices: [REGION, TIMESLICE, TECHNOLOGY, MODE_OF_OPERATION, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
SalvageValue:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
SalvageValueStorage:
    indices: [REGION, STORAGE, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
StorageLevelDayTypeFinish:
    indices: [REGION, STORAGE, SEASON, DAYTYPE, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
StorageLevelDayTypeStart:
    indices: [REGION, STORAGE, SEASON, DAYTYPE, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
StorageLevelSeasonStart:
    indices: [REGION, STORAGE, SEASON, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
StorageLevelYearStart:
    indices: [REGION, STORAGE, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
StorageLevelYearFinish:
    indices: [REGION, STORAGE, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
TotalAnnualTechnologyActivityByMode:
    indices: [REGION, TECHNOLOGY, MODE_OF_OPERATION, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
TotalCapacityAnnual:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
TotalDiscountedCost:
    indices: [REGION,YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
TotalTechnologyAnnualActivity:
    indices: [REGION, TECHNOLOGY, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: True
TotalTechnologyModelPeriodActivity:
    indices: [REGION, TECHNOLOGY]
    type: result
    dtype: float
    default: 0
    calculated: True
Trade:
    indices: [REGION, REGION, TIMESLICE, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
UseByTechnology:
    indices: [REGION, TIMESLICE, TECHNOLOGY, FUEL, YEAR]
    type: result
    dtype: float
    default: 0
    calculated: False
